---
title: "fixed effect"
author: "Jonathan Arve Thomsen"
date: "2025-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data
```{r}
library(readxl)
library(dplyr)
library(ggplot2)
data <- read_excel("data.xlsx", range = "A1:G261")

#laver relative revenue og lønninger
df <- data %>%
  group_by(season) %>%
  mutate(relative_revenue = revenue / mean(revenue)) %>%
  mutate(revenue_Zscore = (revenue - mean(revenue)) / sd(revenue)) %>%
  mutate(relative_wage = wage / mean(wage)) %>%
  mutate(wage_Zscore = (wage - mean(wage)) / sd(wage)) %>%
  mutate(relative_transfer = `transfers (ind-ud)` / mean(`transfers (ind-ud)`)) %>%
  mutate(transfer_Zscore = (`transfers (ind-ud)` - mean(`transfers (ind-ud)`)) / sd(`transfers (ind-ud)`)) %>%
  ungroup()

#laver SRS og relativ point
df <- df %>%
  group_by(season) %>%
  mutate(relative_point = points / mean(points)) %>%
  mutate(point_Zscore = (points - mean(points)) / sd(points)) %>%
  mutate(ppg = points / 38) %>% 
  mutate(ppg_Zscore = (points - mean(points)) / sd(points)) %>%
  ungroup() %>%
  mutate('w%r' = wage / revenue)
```

## Plot med relative wage og point
```{r}
model1 <- lm(relative_point ~ relative_wage, data = df)
r_squared1 <- summary(model1)$r.squared

ggplot(df, aes(x = relative_wage, y = relative_point)) +
  geom_point(color = "#007fa3") +
  geom_smooth(method = "lm", se = FALSE, color = "#211A52") +
  theme_minimal() +
    labs(title = "Relative lønninger og relative point",
       y = "Relativ point", 
       x = "Relativ løn",
       caption = "Kilde: Egne beregninger") + 
  annotate("text", x = max(df$relative_wage) * 0.88, y = max(df$relative_point) * 0.95,
           label = paste("R² = ", round(r_squared1, 2)), color = "#211A52", size = 3.7)

```

## Plot med relative omsætning og point
```{r}
model2 <- lm(relative_point ~ relative_revenue, data = df)
r_squared2 <- summary(model2)$r.squared

ggplot(df, aes(x = relative_revenue, y = relative_point)) +
  geom_point(color = "#007fa3") +
  geom_smooth(method = "lm", se = FALSE, color = "#211A52") +
  theme_minimal() +
    labs(title = "Relative omsætning og relative point",
       y = "Relativ point", 
       x = "Relativ omsætning",
       caption = "Kilde: Egne beregninger") +
  annotate("text", x = max(df$relative_wage) * 0.88, y = max(df$relative_point) * 0.96,
           label = paste("R² = ", round(r_squared2, 2)), color = "#211A52", size = 3.7)

```

#F test for fixed effects
```{r}
library(plm)

df$club <- as.factor(df$club)  # Klubnavn som faktor
df$season <- as.character(df$season)  # Sæson som karakter, hvis den ikke er numerisk

data <- pdata.frame(df, index = c("club", "season"))

# OLS-model (uden fixed effects)
ols_model <- plm(points ~ relative_revenue + relative_wage, data = data, model = "pooling")


# Fixed effects-model
fe_model <- plm(points ~ relative_revenue + relative_wage, data = data, model = "within")

# F-test for fixed effects
pFtest(fe_model, ols_model)

```

#Hausman test
```{r}
# Random Effects-model
re_model <- plm(points ~ relative_revenue + relative_wage, data = data, model = "random")

# Hausman-test for at sammenligne Fixed Effects vs Random Effects
phtest(fe_model, re_model)

```
#Random effects model
```{r}
re_model <- plm(points ~ relative_revenue + relative_wage, data = data, model = "random")
summary(re_model)

coeftest(re_model, vcov = vcovHC(re_model, type = "HC1"))

```

#F test for fixed effects uden de klubber der har været der mindre end 7 sæsoner
```{r}
#Filtrering af data
data_filtered <- subset(df, !club %in% c("Birmingham", "Blackburn", "Blackpool", "Bolton", "Bournemouth", "Brentford", "Brighton", "Cardiff", "Huddersfield", "Hull", "Leeds", "Middlesbrough", "Norwich", "Nottingham", "QPR", "Reading", "Sheffield United", "Watford", "Wigan"))

# Lav pdata.frame
data_filtered <- pdata.frame(data_filtered, index = c("club", "season"))

# OLS-model (uden fixed effects)
ols_model <- plm(points ~ relative_revenue + relative_wage, data = data_filtered, model = "pooling")

# Fixed effects-model
fe_model <- plm(points ~ relative_revenue + relative_wage, data = data_filtered, model = "within")

# F-test for fixed effects
pFtest(fe_model, ols_model)

```


# Test for kun wage
```{r}
# OLS-model (uden fixed effects)
ols_model1 <- plm(points ~  relative_wage, data = data_filtered, model = "pooling")


# Fixed effects-model
fe_model1 <- plm(points ~  relative_wage, data = data_filtered, model = "within")


# F-test for fixed effects
pFtest(fe_model1, ols_model1)
```

## Test med wage, revenue og transfers (Zscore)
### OLS vs. fixed effects
```{r}
# OLS-model (uden fixed effects)
ols_model2 <- plm(point_Zscore ~  revenue_Zscore + wage_Zscore + transfer_Zscore, data = data_filtered, model = "pooling")


# Fixed effects-model
fe_model2 <- plm(point_Zscore ~  wage_Zscore + revenue_Zscore + transfer_Zscore, data = data_filtered, model = "within")
summary(fe_model2)

# F-test for fixed effects
pFtest(fe_model2, ols_model2)
```
### Random vs fixed
```{r}
# Random Effects-model
re_model2 <- plm(point_Zscore ~ revenue_Zscore + wage_Zscore + transfer_Zscore, data = data, model = "random")

# Hausman-test for at sammenligne Fixed Effects vs Random Effects
phtest(fe_model2, re_model2)


```


## Correlations tabel
```{r}
cor_with_p <- function(x) {
  n <- ncol(x)
  corr_mat <- matrix(NA, n, n)
  p_mat <- matrix(NA, n, n)
  colnames(corr_mat) <- rownames(corr_mat) <- colnames(x)
  colnames(p_mat) <- rownames(p_mat) <- colnames(x)
  
  for (i in 1:n) {
    for (j in 1:n) {
      test <- cor.test(x[[i]], x[[j]], use = "pairwise.complete.obs")
      corr_mat[i, j] <- test$estimate
      p_mat[i, j] <- test$p.value
    }
  }
  
  list(correlation = corr_mat, p_value = p_mat)
}

vars <- data[, c("wage", "revenue", "transfers..ind.ud.", "points")]
result <- cor_with_p(vars)

# Add significance stars
star_matrix <- function(corr, p) {
  stars <- ifelse(p < 0.001, "***",
            ifelse(p < 0.01, "**",
            ifelse(p < 0.05, "*",
            ifelse(p < 0.1, ".", " "))))
  rounded_corr <- round(corr, 2)
  paste0(rounded_corr, stars)
}

# Apply and print
corr_table <- matrix(star_matrix(result$correlation, result$p_value),
                     nrow = ncol(vars), ncol = ncol(vars),
                     dimnames = list(colnames(vars), colnames(vars)))
print(corr_table, quote = FALSE)


```

