---
title: "Goal! replikation"
output: html_document
date: "2025-03-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dataformatering
```{r}
library(readxl)
library(dplyr)
library(plm)
library(lmtest)
data <- read_excel("data.xlsx", sheet = "Sheet1", range = "A1:I261")
data2 <- read_excel("data.xlsx",sheet = "Ark1", range = "A1:I313")

data2 <- data2 %>%
  mutate(placering = placering + 20)

ny_data <- rbind(data, data2)

#fjerner klubber, hvor revenue ikke er opgivet
ny_data <- ny_data %>% filter(!is.na(revenue))

#fjerner transfer kolonne
ny_data <- ny_data %>% select(-'transfers (ind-ud)')


#Formatering af lavet ud fra den i GOAL!
df <- ny_data %>%
  group_by(season) %>%
  mutate(log_revenue = log(revenue / mean(revenue))) %>% 
  mutate(log_wage = log(wage / mean(wage))) %>%
  #mutate(log_point = log(points / (114+1-points))) %>% # i stedet for placering anvendes point, der plusses med 1 for at undgå division med 0 (selvom ingen klubber har fået 114 eller 0 point i PL nogensinde, men sikrer sig mod, hvis det skulle ske og kode/metode skal genanvendes til det)
  mutate(log_rank = log((45-placering) / placering)) %>% # GOAL!'s variable for præstation
  mutate(log_tilskuere = log(tilskuere / mean(tilskuere))) %>%
  mutate(log_goals = log(goals / mean(goals))) %>%
  ungroup()

#laver sæson til numerisk tal 10_11 -> 2010
df$season_numeric <- as.numeric(sub("_.*", "", df$season))
df$season_numeric <- ifelse(df$season_numeric < 50, df$season_numeric + 2000, df$season_numeric + 1900)

df$club   <- as.factor(df$club)

#fjerner covid 2020/2021 sæson
covid_df <- df %>%
  filter(season != "20_21")

#minimum antal sæsoner (7)
covid_valid_clubs <- covid_df %>%
  group_by(club) %>%
  summarise(n_seasons = n()) %>%
  filter(n_seasons >= 7) %>% 
  pull(club)

covid_data_filtered <- covid_df %>%
  filter(club %in% covid_valid_clubs)

covid_pdata <- pdata.frame(covid_df, index =c("club", "season_numeric"))
covid_pdata_filtered <- pdata.frame(covid_data_filtered, index =c("club", "season_numeric"))

```

## Test af OLS, RE eller FE
### Performance
```{r}
fe_perform <- plm(log_rank ~ log_wage + lag(log_rank, 1) + log_goals, data = covid_pdata_filtered,
  model = "within"  # eller "pooling", "random", etc. afhængigt af hvad du laver
)

re_perform <- plm(log_rank ~ log_wage + lag(log_rank, 1) + log_goals, data = covid_pdata_filtered,
  model = "random"  # eller "pooling", "random", etc. afhængigt af hvad du laver
)

hausman_test <- phtest(fe_perform, re_perform)
print(hausman_test)

ols_perform <- plm(log_rank ~ log_wage + lag(log_rank, 1) + log_goals, data = covid_pdata_filtered, model = "pooling")


# FE eller OLS?
pFtest(fe_perform, ols_perform)
```

### Revenue
```{r}
fe_revenue <- plm(
  log_revenue ~ log_rank + lag(log_revenue, 1) + log_tilskuere,
  data = covid_pdata_filtered,
  model = "within"  # eller "pooling", "random", etc. afhængigt af hvad du laver
)
re_revenue <- plm(
  log_revenue ~ log_rank + lag(log_revenue, 1) + log_tilskuere,
  data = covid_pdata_filtered,
  model = "random"  # eller "pooling", "random", etc. afhængigt af hvad du laver
)

hausman_test_revenue <- phtest(fe_revenue, re_revenue)
print(hausman_test_revenue)

# FE eller OLS?
ols_revenue <- plm(log_revenue ~ log_rank + lag(log_revenue, 1) + log_tilskuere, data = covid_pdata_filtered, model = "pooling")
pFtest(fe_revenue, ols_revenue)

```


## Revenue regression
### Covid
```{r}
#replikation af GOAL!
covid_fe_revenue <- plm(
  log_revenue ~ log_rank + lag(log_revenue, 1),
  data = covid_pdata_filtered,
  model = "within"  # eller "pooling", "random", etc. afhængigt af hvad du laver
)
summary(covid_fe_revenue)

#+ tilskuere
covid_fe_revenue2 <- plm(
  log_revenue ~ log_rank + lag(log_revenue, 1) + log_tilskuere,
  data = covid_pdata_filtered,
  model = "within"  # eller "pooling", "random", etc. afhængigt af hvad du laver
)
summary(covid_fe_revenue2)
```

#### Diagnostics
```{r}
#within_intercept(plm_model_filtered) #forsøg på at få intercept

#diagnostics
#pbgtest(plm_model_filtered)
#pwartest(plm_model_filtered)
#pcdtest(plm_model_filtered, test = "cd")
#resettest(plm_model_filtered) kan ikke køres

#coeftest(plm_model_filtered, vcov = vcovHC(plm_model_filtered, type = "HC1", cluster = "group"))
```

## Performance regression
### Filtreret datasæt
```{r}
fe_perform_original <- plm(log_rank ~ log_wage + lag(log_rank, 1), data = covid_pdata_filtered,
  model = "within"  # eller "pooling", "random", etc. afhængigt af hvad du laver
)
summary(fe_perform_original)

#+log_goals
summary(fe_perform)
fixef(fe_perform)

#fjerner lag log_rank = bedre forklaring
fe_perform2 <- plm(log_rank ~ log_wage + log_goals, data = covid_pdata_filtered,
  model = "within"  # eller "pooling", "random", etc. afhængigt af hvad du laver
)
summary(fe_perform2)
```
#### Diagnostics
```{r}
#pbgtest(perform_model_filtered)
#pwartest(perform_model_filtered)
#pcdtest(perform_model_filtered, test = "cd")
```


## Win-maximization
$$P_{it}^*=\frac{21}{1+exp(\frac{a+b_i+c(\alpha+\beta_i)+c\;ln\bar{R_t}-c\;ln\bar{W_t}}{c\gamma-1})}$$

## Profit-maximization
$$P_{it}^*=\frac{21}{1+exp(\frac{a+b_i+c(\alpha+\beta_i)+c\;ln\bar{R_t}-c\;ln\bar{W_t}+c\;ln(c\gamma)}{c\gamma-1})}$$

##forsøg på at replikere manchester uniteds positioner i paper
```{r}
beta <- 0.7476
b <- 1.4442
a <- -0.4145
alpha <- -0.945
gamma <- 0.2274
c <- 1.2581
R <- 25860.75
W <- 16165.880
#profit
45 / (1+exp((a + b + c * (alpha+beta) + c * log(R) - c * log(W) + c * log(c*gamma) ) / (c*gamma -1) ))

#win
45 / (1+exp((a + b + c * (alpha+beta) + c * log(R) - c * log(W)) /(c*gamma -1) ))
```


